#ifndef SEQUENCES_HPP
#define SEQUENCES_HPP

enum SEQUENCE_NAME {
  SEQUENCE_ALARM = 0,
  SEQUENCE_DRINK,
  SEQUENCE_DISAPP,
  SEQUENCE_ANXIOUS_SOUND,
  SEQUENCE_SURPRISED_SOUND,
  SEQUENCE_IMPRESSED_SOUND,
  SEQUENCE_MAX
};

#endif